### ISSUE TITLE
CAV Conceptual Model: What is the use of CriterionEvaluationContext?

### ISSUE THREAD

**Issue by paulakeen** [isa-camss/CAV#1]
On behalf of some newcomers who wonder what is the meaning and use of the CriterionEvaluationContext class in the Core Assessment Vocabulary:

In the narrative of the specification document, it is explained that "Criteria can themselves be simple or complex and originate from various reference sources. The overall context for the evaluation of the Criteria is provided by the Scenario, however in case certain  
additional contextualisation or **_evaluation instructions_** these can exceptionally be provided by means of CriterionEvaluationContexts.

In the end, Scenarios are intended to put criteria together aiming to a specific purpose; whilst the Criterion**Evaluation**Context is intended to add methodological instruments that specify/clarify how the criteria are to be evaluated given the Scenario (i.e. a kind of meta-scenario). 

 The definition of the class confirms it: "The context for a criterion providing guidance on its evaluation considering the given scenario. This is used exceptionally to extend the context offered by the scenario when it is not sufficient for the
evaluation of a given criterion." (one and only one given criterion).

If you have a look into the UML model, you will observe that the cardinality between the class 'CriterionEvaluationContext' and 'Criterion' is '1'. And, by the way, the 'Score' is 'basedOn' this 'CriterionEvaluationContext'. This design would support the inclusion of 'Formula' inside the class 'CriterionEvaluationContext', since the formula would provide the exact means (context) for the production of the Score and for its automated evaluation.

These reflections should be taken as food-for-thought for the evolution of the CAV, e.g.:
1- Inclusion of Formula,
2- Revision of the term 'basedOn' for the predicate going from 'Score' to 'CriterionEvaluationContext', and 
3- An inverse property for it, going from CriterionEvaluationContext towards 'Score', since it seems more logical that the formula (if it ends up there, in the CriterionEvaluationContext) is used to calculate the score.

![Captura de pantalla 2020-10-05 a las 15 44 55](https://user-images.githubusercontent.com/16134316/95087440-f7583380-0721-11eb-89bd-12fe8264521f.png)

**Comment by jseguraf** [comment]
The decission mades regarding this issue are spread in a couple of other issues, but mainly in issue #3 . 

To sum up, these decissions were: 

* Change the name of the CriterionEvaluationContext into EvaluationContext, to make it more generic and extensible. 
* Algorithms, formuale and other complexities have to be excluded from "Core Vocabularies". Use application profiles if you need to extend the core vocabulary with these "resources". Precisely, with this purpose in mind an attribute pointing to an rdfs:Resource. This allows to apply different algorithms and formulae to the same criteria depending on the Scenario and the particular EvaluationContext.
