### ISSUE TITLE
Potential further clarifications in the definitions of cav:Type and cav:Interpretation (of cav:Statement)

### ISSUE THREAD

**Issue by costas80** [isa-camss/CAV#11]
The definition of cav:Interpretation suggests (nicely) that:

> Different domains could use different code list to express this (e.g. positive, negative, neutral). 

It would be useful in my opinion to include such a clarification on cav:Type as well given that the rationale is similar. In short, these are generic concepts (hence their definition in the CAV) but with typically domain-specific values (hence their generic type). It could be interesting to ensure that both definitions suggest them as likely extension points for specific use cases.

**Comment by paulakeen** [comment]
See also this [Comment](https://github.com/isa-camss/CAV/issues/7#issuecomment-705702810) to Issue #7 .

**Comment by jseguraf** [comment]
Clarifications of both concepts have been provided.
