### ISSUE TITLE
Rename CriterionEvaluationContext to be more abstract and flexible

### ISSUE THREAD

**Issue by costas80** [isa-camss/CAV#13]
Checking issue #2 raised by @paulakeen I think it is important to rename class cav:CriterionEvaluationContext to have better flexibility in light of CCCEV changes. As it stands cav:Statements, cav:Scenarios, cav:Scores etc. refer to cccev:Criteria however we never see the term "criterion" mentioned elsewhere. The exception is the cav:CriterionEvaluationContext which is meant to provide additional contextualisation for a criterion's evaluation.

If in the future we decide that the CAV should not refer to cccev:Criteria but rather to e.g. cccev:Requirements, or even something completely different for that matter, we will be left with a badly named concept cav:CriterionEvaluationContext. I understand that this would be a potentially fundamental change but it seems as good future-proofing to not assume that we are always referring to something called a criterion.

My proposal would be to consider a different name for cav:CriterionEvaluationContext such as **cav:SpecificEvaluationContext** or simply **cav:EvaluationContext**. The semantics remain unchanged but we avoid introducing a CCCEV class name in a CAV class name. Finally, it is worth noting that the term "criterion" of course appears in various CAV definitions. This isn't a problem however given that definitions can be adapted as editorial changes without problems. Changing in the future a class name, or sticking with an inappropriately named class, is more problematic.

**Comment by paulakeen** [comment]
Completely agree. +1 to cav:EvaluationContext.

**Comment by giorgialodi** [comment]
+1 for cav:EvaluationContext

**Comment by paulakeen** [comment]
The CAMSS WG approves the re-naming of cav:CriterionEvaluationContext to 'cav:EvaluationContext'. A note to attach referred to this class could clarify that "this context is to be added exceptionally", as explained in the definition: "the context for a criterion providing guidance on its evaluation considering the given scenario. This is used exceptionally to extend the
context offered by the scenario when it is not sufficient for the evaluation of a given criterion.).
