### ISSUE TITLE
ccev:ReferenceFramework in the diagram

### ISSUE THREAD

**Issue by giorgialodi** [isa-camss/CAV#18]
In the diagram I noticed some concepts coming from the CCEV vocabulary. I do not find ReferenceFramework in version 2.0.0. I found FormalFramework that is BTW in the CPSV vocabulary, if we mean a legal framework in which a criterion can be defined.

In addition, a FormalFramework is a dataset? Or more generally speaking a dcat:Resource? This axiom regarding the FormalFramework  subClassOf dcat:Dataset, is it defined in the context of CAV?

**Comment by paulakeen** [comment]
@giorgialodi: the FormalFramework was defined in v1.0.0 of the CCCEV. The latest version of the CCCEV is v2.0.0 and can be found in the [CCCEV](file:///Users/macmini/Downloads/CCCEV-2.0.0-Specification.pdf) GitHub repository.

The WG proposes to remove everything coming from the CCCEV that is not the Criterion class (which in the end is the only thing we need to connect with the CAV).
