### ISSUE TITLE
Dependency of the CAV from the new CCCEV

### ISSUE THREAD

**Issue by paulakeen** [isa-camss/CAV#2]
As you may know the CCCEV (Core Criterion and Core Evidence Vocabulary) has been evolving lately into its version 2.0.0. 

In this recent version, maintained by SEMIC, the 'central' (core) class is not 'Criterion' anymore, but 'Requirement', a quite abstract class that is the base for Criterion, Information Requirement, Constraint....

Question:

Does this evolution entail that the CAV should not be connected to 'Criterion' from now on, but to 'Requirement'?

In the end, the Scenario groups criteria, and what is being evaluated are criteria......Reactions would be appreciated.

**Comment by paulakeen** [comment]
See also Issue #13  .

**Comment by paulakeen** [comment]
Our opinion, unless otherwise convinced, is that in the CAV we only evaluate criteria. We do not evaluate Information Requirements, Constraints, nor other possible future descendants of Requirement (as they are currently defined in the CCCEV). 

Another rationale for this could be: the data needed for evaluation and assessment are all in the cccev:Criterion, e.g. the weight, the weighing considerations, the score, additionally to the name, type and description of the thing that is to be evaluated. By the way, the definition of Criterion is 'a condition for evaluation', which is the main function of CAV!

**Comment by jseguraf** [comment]
Decission: The WG agreed to link to requirement.
