### ISSUE TITLE
Capturing and parsing formulae for the criterion evaluation score

### ISSUE THREAD

**Issue by paulakeen** [isa-camss/CAV#3]
The score of an objective, i.e. non-qualitative, criteria can/should be calculated based on a formula. The current version of the CAV does not have any placeholder for formulae. 

In issue #1 the proposal issued is to use the Class _CriterionEvaluationContext_, which points always to 1 Score to include a field 'Formula' or to link to a sub-model or sub-ontology that represents the 'Formula'.

For sure there must exist out there more than one representation of formulae an equations that can be automatically parsed, validated and processed to cast the _evaluation_ resulting score. 

**QUESTION** : _What should we use in CAV for the representation of a formula?_

Two preliminary suggestions were:

1. Consider using the LaTex syntax for mathematical equations
2. Consider using [W3C MathML](https://www.w3.org/Math/) 
3. Other

(BTW, this raises another subject that should be discussed in this forum: what is the difference between evaluation and assessment? Can formulae be used for 'the calculation of an assessment'? Please feel free to comment on this other issue in Issue #4 ).

**Comment by costas80** [comment]
Interesting idea but I fear that this could be a door leading to much complexity. If we start with formulae (which not all assessments would include by the way) we could be tempted to extend to things like value ranges, weights, prerequisites, sub-criteria etc. If possible I would have such details be captured (ideally) within the CCCEV (and not the CAV) or, if not possible within the CCCEV, an application profile.

I understand that this relates to the notion of evaluation vs assessment (see #4) and the precise purpose of CriterionEvaluationContext (see #1). In my view however CriterionEvaluationContext should add contextualisation (hence the "Context" suffix), extending the narrative of the scenario, but not offering something as concrete as a formula.

Looking forward to discussing this :)

**Comment by paulakeen** [comment]
After discusion on whether to have formulae or not in the CAV the conclusions and decisions made by the CAMSS WG are:

Somehow link the EvaluationContext to a 'resource' that can could be, amongst other things, a formula.

Proposal for further, future, discussions could be:

* Add a property linking the EvaluationContext to **dcat:Resource**, or may be **rdf:Resource** (to discuss pros-and-cons of both approaches, rdf:resource would provide more flexibility to link not only to publishable resources but also to application profiles, models, etc.)
* Make the EvaluationContext a subClassOf dcat:Resource;

We need to further discuss this topic.

**Comment by jseguraf** [comment]
See issue #1 .
