### ISSUE TITLE
use and definition of Property TriggeredFrom 

### ISSUE THREAD

**Issue by guascce** [isa-camss/CAV#8]
I do not understand the context of use of such a property an dwhether it is really core.
I am not sur ethat defining it as 'The event causing the current assessment' when the current assessment my be caused by something different of a previous assessment,... this is puzzling.

**Comment by jseguraf** [comment]
Let's discuss it, but we tend to agree that it doesn't seem core. 

This was suggested by one member of the CAV working group. We can ask him in which contexts he considers it makes sense, and then we can see if it is sufficiently generic or not.

**Comment by costas80** [comment]
Not sure I agree with @guascce given that TriggeredFrom is defined as

> The event causing the current assessment **as the result of another related assessment**.

In my view this does not create ambiguity with respect to assessments not triggered by other assessments. In addition, this doesn't seem use-case specific and in any case it is optional so it doesn't cause issues for the core assessment concept. Let's discuss :)

**Comment by paulakeen** [comment]
Today we bumped into an interesting situation that, perhaps, is also related to this issue:

What if you need to issue an assessment that takes as inputs other assessments?

In principle, the CAV would allow for this, since the cardinality between Statement and Criterion is 0..*

**Comment by costas80** [comment]
On the triggeredFrom topic I believe it would be best to consider this as having 0..* cardinality as opposed to 0..1. This is based on the use case offered by @paulakeen where an assessment would be triggered from multiple other assessments. Taking procurement as an example where we have two proposals we would:

1. Assess each proposal (i.e. two assessments).
2. Assess the overall award only once we have assessed the proposals.

In this case it could be meaningful to express that the award assessment is triggered from the proposal assessments (which would be like prerequisites, not necessarily inputs in the general case).

**Comment by costas80** [comment]
See #14

**Comment by jseguraf** [comment]
The latest proposal by @paulakeen and @costas80  after discussion was approved. See issue #14 for more details.
