### ISSUE TITLE
question on the predicates hasSummary and hasReport 

### ISSUE THREAD

**Issue by guascce** [isa-camss/CAV#9]
I have been questionning myself whether the range Distribution of those predicates was sufficient to ensure that there would be content in the reports.
So if there is an instance of a distribution , does it mean that the information (the content of the report) is conveyed by an instance of Dataset.

**Comment by paulakeen** [comment]
Well, the distribution can be manifested in may different ways, for example another RDF that models reports in a different namespace (...if i understood well the issue).

**Comment by costas80** [comment]
The knowledge produced by a cav:Assessment is collected in cav:Statements, not the distributions. These distributions are physical manifestations/representations of the overall assessment. As such an "empty" assessment (in terms of results) is one that has no statements.

Splitting these in a summary and report allows differentiation between different expected types of such representations (with of course additional being able to be added in subclasses or application profiles).

**Comment by jseguraf** [comment]
Very related to this issue is, maybe, the comment by @giorgialodi where she wonders  whether the assessment of our model is an event or an object. From the foundational ontoengeenering they are totally different (see issue #15 ).

**Comment by jseguraf** [comment]
It is clear for the WG that the assessment is the result of the action of assessing and that it resolves in stating judgements based on the evaluation of the criteria (see the cav:Statement class and its definition for more details). The properties that link the cav:Assessment to the dcat:Distribution, contribute to better clarify that the assessment is made of data and that it may have many different manifestations and expressions (via the dcat:Distribution class).
